[package]
name = "zino-model"
description = "Domain models for zino."
version = "0.14.0"
rust-version = "1.73"
edition = "2021"
license = "MIT"
categories = ["web-programming", "database"]
keywords = ["web", "model", "orm", "schema"]
homepage = "https://github.com/photino/zino"
repository = "https://github.com/photino/zino"
documentation = "https://docs.rs/zino-model"
readme = "README.md"

[features]
default = [
    "namespace",
    "visibility",
    "tags",
    "owner-id",
    "maintainer-id",
    "edition",
]
namespace = []
visibility = []
tags = []
owner-id = []
maintainer-id = []
edition = []

[dependencies]
regex = "1.10.2"
sqlx = "0.7.2"
tracing = "0.1.40"

[dependencies.serde]
version = "1.0.193"
features = ["derive"]

[dependencies.strum]
version = "0.25.0"
features = ["derive"]

[dependencies.zino-core]
path = "../zino-core"
version = "0.17.0"
features = [
    "orm",
    "validator-email",
    "validator-phone-number",
]

[dependencies.zino-derive]
path = "../zino-derive"
version = "0.14.0"
