[package]
name = "zino-model"
description = "Model types for zino."
version = "0.3.2"
rust-version = "1.68"
edition = "2021"
license = "MIT"
homepage = "https://github.com/photino/zino"
repository = "https://github.com/photino/zino"
documentation = "https://docs.rs/zino-model"
readme = "README.md"

[dependencies]
serde = { version = "1.0.152", features = ["derive"] }

[dependencies.zino-core]
path = "../zino-core"
version = "0.4.0"

[dependencies.zino-derive]
path = "../zino-derive"
version = "0.3.2"