[package]
name = "zino-model"
version = "0.2.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.152", features = ["derive"] }
serde_json = { version = "1.0.91" }

[dependencies.zino-core]
path = "../zino-core"
version = "0.2.0"

[dependencies.zino-derive]
path = "../zino-derive"
version = "0.2.0"