[package]
name = "zino-model"
description = "Model types for zino."
version = "0.5.2"
rust-version = "1.70"
edition = "2021"
license = "MIT"
categories = ["web-programming", "database"]
keywords = ["web", "model", "orm", "schema"]
homepage = "https://github.com/photino/zino"
repository = "https://github.com/photino/zino"
documentation = "https://docs.rs/zino-model"
readme = "README.md"

[dependencies]
apache-avro = "0.14.0"
regex = "1.8.1"

[dependencies.serde]
version = "1.0.159"
features = ["derive"]

[dependencies.zino-core]
path = "../zino-core"
version = "0.8.2"
features = ["orm"]

[dependencies.zino-derive]
path = "../zino-derive"
version = "0.5.4"