[package]
name = "zino-model"
description = "Domain models for zino."
version = "0.9.2"
rust-version = "1.72"
edition = "2021"
license = "MIT"
categories = ["web-programming", "database"]
keywords = ["web", "model", "orm", "schema"]
homepage = "https://github.com/photino/zino"
repository = "https://github.com/photino/zino"
documentation = "https://docs.rs/zino-model"
readme = "README.md"

[features]
default = [
    "namespace",
    "visibility",
    "tags",
    "owner-id",
    "maintainer-id",
    "edition",
]
namespace = []
visibility = []
tags = []
owner-id = []
maintainer-id = []
edition = []

[dependencies]
regex = "1.9.4"
strum_macros = "0.25.2"

[dependencies.serde]
version = "1.0.188"
features = ["derive"]

[dependencies.zino-core]
path = "../zino-core"
version = "0.12.2"
features = ["orm"]

[dependencies.zino-derive]
path = "../zino-derive"
version = "0.9.2"
