# --env=prod

name = "data-cube"
version = "0.6.4"

[dirs]
uploads = "local/uploads"

[debug]
host = "127.0.0.1"
port = 6070

[main]
host = "127.0.0.1"
port = 6080

[[standby]]
name = "portal"
host = "127.0.0.1"
port = 6081

[[standby]]
name = "admin"
host = "127.0.0.1"
port = 6082

[database]
type = "postgres"
namespace = "dc"

[[postgres]]
host = "127.0.0.1"
port = 5432
database = "data_cube"
username = "postgres"
password = "uzU7eGgSw6HLp63qbjpMQMnl4Kk0SrDDp9bIXkRmcjqwRFRf"

[[sqlite]]
database = "local/data/main.db"

[tracing]
filter = "warn"

[metrics]
exporter = "prometheus"
host = "127.0.0.1"
port = 9000

[[connector]]
type = "arrow"
name = "mock"
root = "local/data/mock/"

[[connector.tables]]
type = "csv"
name = "users"
path = "users.csv"

[[connector.tables]]
type = "ndjson"
name = "logs"
url = "http://localhost:6080/public/data/logs.ndjson"

[connector.tables.schema]
timestamp = "string"
level = "string"
fields = { message = "string" }
target = "string"
span = { "http.method" = "string", "http.target" = "string", "http.status_code" = "int" }

[connector.variables]
app-name = "data-cube"

[openapi]
show-docs = true
