# --env=dev

name = "data-cube"
version = "0.6.2"

[dirs]
uploads = "local/uploads"

[debug]
host = "127.0.0.1"
port = 6070

[main]
host = "127.0.0.1"
port = 6080

[[standby]]
name = "portal"
host = "127.0.0.1"
port = 6081

[[standby]]
name = "admin"
host = "127.0.0.1"
port = 6082

[database]
namespace = "dc"
max-rows = 10000

[[mysql]]
host = "127.0.0.1"
port = 3306
database = "data_cube"
username = "root"
password = "Lv2OvgIj2FvuDPa9gTwBwUrVQhL/GG+mHC6SFqm8ZFo"

[[postgres]]
host = "127.0.0.1"
port = 5432
database = "data_cube"
username = "postgres"
password = "Wp6igv6c/+W0x7TCz2d7X3UPv0cYSCiXGM4fIxwbeNpNB8cA"

[[sqlite]]
database = "local/data/main.db"

[tracing]
filter = "info,sqlx=info,zino=trace,zino_core=trace"

[metrics]
exporter = "prometheus"
host = "127.0.0.1"
port = 9000

[jwt]
max-age = "20m"
refresh-interval = "7d"

[[connector]]
type = "arrow"
name = "mock"
root = "./local/data/mock/"

[[connector.tables]]
type = "csv"
name = "users"
path = "./users.csv"

[[connector.tables]]
type = "ndjson"
name = "logs"
url = "http://localhost:6080/public/data/logs.ndjson"

[connector.tables.schema]
timestamp = "string"
level = "string"
fields = { message = "string" }
target = "string"
span = { "http.method" = "string", "http.target" = "string", "http.status_code" = "int" }

[connector.variables]
app-name = "data-cube"

[openapi]
custom-html = "local/docs/rapidoc.html"
