# --env=dev

name = "data-cube"
version = "0.6.0"

[main]
host = "127.0.0.1"
port = 6080

[[standby]]
host = "127.0.0.1"
port = 6081

[[standby]]
host = "127.0.0.1"
port = 6082

[database]
namespace = "dc"
max-rows = 10000

[[mysql]]
host = "127.0.0.1"
port = 3306
database = "data_cube"
username = "root"
password = "Er/DkSLyeOsUiHXHK4hO7E8fdl1g8Qwy2Ef8mR1/4BQ"

[[postgres]]
host = "127.0.0.1"
port = 5432
database = "data_cube"
username = "postgres"
password = "9jMzf8xZSrC3kO2okJUL9XGvFWyzh1VDJwBIJ9e78NsRfJkp"

[tracing]
filter = "info,sqlx=info,zino=trace,zino_core=trace"

[metrics]
exporter = "prometheus"
host = "127.0.0.1"
port = 9000

[[connector]]
type = "arrow"
name = "mock"
root = "./assets/data/mock/"

[[connector.tables]]
type = "csv"
name = "users"
path = "./users.csv"

[[connector.tables]]
type = "ndjson"
name = "logs"
url = "http://localhost:6080/public/data/logs.ndjson"

[connector.tables.schema]
timestamp = "string"
level = "string"
fields = { message = "string" }
target = "string"
span = { "http.method" = "string", "http.target" = "string", "http.status_code" = "int" }

[connector.variables]
app-name = "data-cube"
