# --env=dev

name = "data-cube"
version = "0.5.4"

[main]
host = "127.0.0.1"
port = 6080

[[standby]]
host = "127.0.0.1"
port = 6081

[[standby]]
host = "127.0.0.1"
port = 6082

[database]
namespace = "dc"

[[mysql]]
host = "127.0.0.1"
port = 3306
database = "data_cube"
username = "root"
password = "uVJFx2Zjrp8zCVnzN79IaSvKBbxNiAp9K3RNlV3IglE"

[[postgres]]
host = "127.0.0.1"
port = 5432
database = "data_cube"
username = "postgres"
password = "pYQoeol0v7zr3v7ogRq0rtmdzJHv2xVKJSFp3Yi2eMEIUoub"

[tracing]
filter = "info,sqlx=trace,zino=trace,zino_core=trace"
display-filename = false
display-line-number = false
display-span-list = false

[metrics]
exporter = "prometheus"
host = "127.0.0.1"
port = 9000

[[connector]]
type = "arrow"
name = "mock"
root = "./assets/data/mock/"

[[connector.tables]]
type = "csv"
name = "users"
path = "./users.csv"

[[connector.tables]]
type = "ndjson"
name = "logs"
url = "http://localhost:6080/public/data/logs.ndjson"

[connector.tables.schema]
timestamp = "string"
level = "string"
fields = { message = "string" }
target = "string"
span = { "http.method" = "string", "http.target" = "string", "http.status_code" = "int" }

[connector.variables]
app-name = "data-cube"
