[package]
name = "axum-app"
version = "0.3.1"
rust-version = "1.68"
edition = "2021"
publish = false

[dependencies]
axum = { version = "0.6.1" }
serde_json = { version = "1.0.91" }
tracing = { version = "0.1.37" }

[dependencies.zino]
path = "../../../zino"
version = "0.3.1"
features = ["axum-server"]

[dependencies.zino-core]
path = "../../../zino-core"
version = "0.3.1"

[dependencies.zino-model]
path = "../../../zino-model"
version = "0.3.1"
