[package]
name = "zino-derive"
description = "Derived traits for zino."
version = "0.13.1"
rust-version = "1.73"
edition = "2021"
license = "MIT"
homepage = "https://github.com/photino/zino"
repository = "https://github.com/photino/zino"
documentation = "https://docs.rs/zino-derive"
readme = "README.md"

[lib]
proc-macro = true

[dependencies]
convert_case = "0.6.0"
proc-macro2 = "1.0.68"
quote = "1.0.33"
syn = "2.0.39"

[dependencies.zino-core]
path = "../zino-core"
version = "0.16.1"
features = ["orm"]
