[package]
name = "zino-derive"
description = "Derived traits for zino."
version = "0.8.2"
rust-version = "1.72"
edition = "2021"
license = "MIT"
homepage = "https://github.com/photino/zino"
repository = "https://github.com/photino/zino"
documentation = "https://docs.rs/zino-derive"
readme = "README.md"

[lib]
proc-macro = true

[dependencies]
convert_case = "0.6.0"
proc-macro2 = "1.0.66"
quote = "1.0.31"
syn = "2.0.27"

[dependencies.zino-core]
path = "../zino-core"
version = "0.11.2"
features = ["orm"]
