[info]
title = "DataCube API"
description = """
An example for [actix-web] integration.

[actix-web]: https://crates.io/crates/actix-web
"""
contact = { url = "https://github.com/zino-rs/zino" }
license = "MIT"
version = "1.0"

[security_schemes.jwt_auth]
type = "http"
scheme = "bearer"
bearer_format = "JWT"

[[securities]]
name = "jwt_auth"
