name = "Tags"
securities = []

[[endpoints]]
path = "/tag/new"
method = "POST"
summary = "Creates a new tag"

[endpoints.body]
schema = "/tag/definition"

[[endpoints]]
path = "/tag/{tag_id}/delete"
method = "POST"
summary = "Deletes a tag by ID"

[[endpoints]]
path = "/tag/{tag_id}/update"
method = "POST"
summary = "Updates a tag by ID"

[endpoints.body]
schema = "/tag/definition?action=update"

[[endpoints]]
path = "/tag/{tag_id}/view"
method = "GET"
summary = "Gets a tag by ID"

[[endpoints]]
path = "/tag/list"
method = "GET"
summary = "Finds a list of tags"

[endpoints.query]
category = { type = "string", description = "Tag category" }
parent_id = { schema = "tagId" }

[schemas.tagId]
type = "string"
format = "uuid"
description = "Tag ID"

[models.tag.visibility]
translations = [
    ["Public", "🌐"],
    ["Internal", "🔵"],
    ["Proteched", "⛔"],
    ["Private", "🔴"],
]

[models.tag.status]
translations = [
    ["Active", "😄"],
    ["Inactive", "😴"],
]
