[package]
name = "zino-core"
description = "Core types and traits for zino."
version = "0.2.2"
rust-version = "1.68"
edition = "2021"
license = "MIT"
categories = ["asynchronous", "network-programming", "web-programming::http-server"]
keywords = ["http", "web", "framework"]
homepage = "https://github.com/photino/zino"
repository = "https://github.com/photino/zino"
documentation = "https://docs.rs/zino-core"
readme = "README.md"

[dependencies]
aes-gcm-siv = { version = "0.11.1" }
async-trait = { version = "0.1.60" }
base64 = { version = "0.20.0" }
bytes = { version = "1.3.0" }
futures = { version = "0.3.25" }
hmac = { version = "0.12.1" }
http = { version = "0.2.8" }
http-body = { version = "0.4.5" }
http-types = { version = "2.12.0" }
rand = { version = "0.8.5" }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = { version = "1.0.91" }
sha2 = { version = "0.10.6" }
sqlx = { version = "0.6.2", features = ["runtime-tokio-native-tls", "postgres", "uuid", "time", "json"] }
time = { version = "0.3.17", features = ["local-offset", "parsing", "serde"] }
tracing = { version = "0.1.37" }
toml = { version = "0.5.10" }
url = { version = "2.3.1" }
uuid = { version = "1.2.2", features = ["serde", "v4"] }