[package]
name = "zino-core"
description = "Core types and traits for zino."
version = "0.6.0"
rust-version = "1.68"
edition = "2021"
license = "MIT"
categories = ["asynchronous", "network-programming", "web-programming::http-server"]
keywords = ["http", "web", "framework"]
homepage = "https://github.com/photino/zino"
repository = "https://github.com/photino/zino"
documentation = "https://docs.rs/zino-core"
readme = "README.md"

[package.metadata.docs.rs]
all-features = true

[features]
default = ["view"]
accessor = ["opendal"]
accessor-ftp = ["accessor", "opendal/services-ftp"]
accessor-ipfs = ["accessor", "opendal/services-ipfs"]
accessor-memcached = ["accessor", "opendal/services-memcached"]
accessor-moka = ["accessor", "opendal/services-moka"]
accessor-redis = ["accessor", "opendal/services-redis"]
cache = ["dep:lru"]
connector = ["connector-mysql", "connector-postgres"]
connector-mssql = ["connector", "sqlx/mssql"]
connector-mysql = ["connector", "sqlx/mysql"]
connector-postgres = ["connector", "sqlx/postgres"]
connector-sqlite = ["connector", "sqlx/sqlite"]
connector-taos = ["connector", "dep:taos"]
view = ["dep:tera"]

[dependencies]
aes-gcm-siv = "0.11.1"
apache-avro = "0.14.0"
async-trait = "0.1.64"
base64-simd = "0.8.0"
bytes = "1.4.0"
cookie = "0.17.0"
cron = "0.12.0"
fluent = "0.16.0"
futures = "0.3.26"
hkdf = "0.12.3"
hmac = "0.12.1"
http = "0.2.8"
http-body = "0.4.5"
intl-memoizer = "0.5.1"
metrics = "0.20.1"
metrics-exporter-prometheus = "0.11.0"
metrics-exporter-tcp = "0.7.0"
parking_lot = "0.12.1"
rand = "0.8.5"
regex = "1.7.1"
reqwest-middleware = "0.2.0"
reqwest-retry = "0.2.1"
reqwest-tracing = "0.4.0"
serde_qs = "0.11.0"
serde_urlencoded = "0.7.1"
sha2 = "0.10.6"
sysinfo = "0.27.7"
task-local-extensions = "0.1.3"
toml = "0.7.2"
tracing = "0.1.37"
tracing-appender = "0.2.2"
url = "2.3.1"

[dependencies.chrono]
version = "0.4.23"
features = ["serde"]

[dependencies.lru]
version = "0.9.0"
optional = true

[dependencies.opendal]
version = "0.27.0"
features = [
    "layers-all",
    "compress",
    "native-tls",
]
optional = true

[dependencies.reqwest]
version = "0.11.14"
features = [
    "cookies",
    "gzip",
    "json",
    "multipart",
    "stream",
    "native-tls",
]

[dependencies.serde]
version = "1.0.152"
features = ["derive"]

[dependencies.serde_json]
version = "1.0.93"
features = ["raw_value"]

[dependencies.sqlx]
version = "0.6.2"
features = [
    "runtime-tokio-native-tls",
    "postgres",
    "uuid",
    "chrono",
    "json",
]

[dependencies.taos]
version = "0.4.18"
default-features = false
features = ["ws"]
optional = true

[dependencies.tera]
version = "1.17.1"
optional = true

[dependencies.tracing-subscriber]
version = "0.3.16"
features = ["env-filter", "json", "local-time"]

[dependencies.unic-langid]
version = "0.9.1"
features = ["macros"]

[dependencies.uuid]
version = "1.3.0"
features = [
    "fast-rng",
    "serde",
    "v4",
    "v7",
]