[package]
name = "zino-core"
description = "Core types and traits for zino."
version = "0.14.0"
rust-version = "1.72"
edition = "2021"
license = "MIT"
categories = ["asynchronous", "network-programming", "web-programming::http-server"]
keywords = ["http", "web", "framework"]
homepage = "https://github.com/photino/zino"
repository = "https://github.com/photino/zino"
documentation = "https://docs.rs/zino-core"
readme = "README.md"

[package.metadata.docs.rs]
features = ["full", "runtime-tokio"]

[features]
accessor = ["opendal"]
accessor-cacache = ["accessor", "opendal/services-cacache"]
accessor-dashmap = ["accessor", "opendal/services-dashmap"]
accessor-dropbox = ["accessor", "opendal/services-dropbox"]
accessor-ftp = ["accessor", "opendal/services-ftp"]
accessor-gdrive = ["accessor", "opendal/services-gdrive"]
accessor-ipfs = ["accessor", "opendal/services-ipfs"]
accessor-memcached = ["accessor", "opendal/services-memcached"]
accessor-mini-moka = ["accessor", "opendal/services-mini-moka"]
accessor-moka = ["accessor", "opendal/services-moka"]
accessor-onedrive = ["accessor", "opendal/services-onedrive"]
accessor-persy = ["accessor", "opendal/services-persy"]
accessor-redb = ["accessor", "opendal/services-redb"]
accessor-redis = ["accessor", "opendal/services-redis"]
accessor-sled = ["accessor", "opendal/services-sled"]
accessor-supabase = ["accessor", "opendal/services-supabase"]
accessor-wasabi = ["accessor", "opendal/services-wasabi"]
all-accessors = [
    "accessor",
    "accessor-cacache",
    "accessor-dashmap",
    "accessor-dropbox",
    "accessor-ftp",
    "accessor-gdrive",
    "accessor-ipfs",
    "accessor-memcached",
    "accessor-mini-moka",
    "accessor-moka",
    "accessor-onedrive",
    "accessor-persy",
    "accessor-redb",
    "accessor-redis",
    "accessor-sled",
    "accessor-supabase",
    "accessor-wasabi",
]
all-chatbots = ["chatbot", "chatbot-openai"]
all-connectors = [
    "connector",
    "connector-arrow",
    "connector-http",
    "connector-mysql",
    "connector-postgres",
    "connector-sqlite",
]
all-formats = ["format", "format-pdf"]
auth-totp = ["dep:totp-rs"]
cache = ["dep:lru"]
chatbot = []
chatbot-openai = ["dep:async-openai", "chatbot"]
connector = ["connector-http"]
connector-arrow = ["dep:datafusion", "connector"]
connector-http = ["connector"]
connector-mysql = ["connector", "sqlx", "sqlx/mysql"]
connector-postgres = ["connector", "sqlx", "sqlx/postgres"]
connector-sqlite = ["connector", "sqlx", "sqlx/sqlite"]
crypto-sm = ["dep:ctr", "dep:sm3", "dep:sm4"]
default = ["runtime-tokio", "tls-rustls"]
format = []
format-pdf = ["format", "dep:printpdf"]
full = [
    "all-accessors",
    "all-chatbots",
    "all-connectors",
    "all-formats",
    "auth-totp",
    "cache",
    "orm",
    "view",
]
orm = ["sqlx", "sqlx/sqlite"]
orm-mysql = ["orm", "sqlx/mysql"]
orm-postgres = ["orm", "sqlx/postgres"]
orm-sqlite = ["orm", "sqlx/sqlite"]
runtime-async-std = ["sqlx?/runtime-async-std"]
runtime-tokio = ["sqlx?/runtime-tokio"]
tls-native = ["opendal?/native-tls", "reqwest/native-tls", "sqlx?/tls-native-tls"]
tls-rustls = ["opendal?/rustls", "reqwest/rustls-tls", "sqlx?/tls-rustls"]
view = ["dep:minijinja"]
view-tera = ["view", "dep:tera"]
view-minijinja = ["view", "dep:minijinja"]

[dependencies]
aes-gcm-siv = "0.11.1"
apache-avro = "0.16.0"
async-trait = "0.1.73"
base64 = "0.21.4"
bytes = "1.5.0"
cfg-if = "1.0"
convert_case = "0.6.0"
cookie = "0.16.2"
cron = "0.12.0"
csv = "1.3.0"
dotenvy = "0.15.7"
etag = "4.0.0"
faster-hex = "0.8.1"
fluent = "0.16.0"
futures = "0.3.28"
hkdf = "0.12.3"
hmac = "0.12.1"
http = "0.2.9"
http-body = "0.4.5"
intl-memoizer = "0.5.1"
jwt-simple = "0.11.7"
metrics = "0.21.0"
metrics-exporter-prometheus = "0.12.1"
mime = "0.3.17"
mime_guess = "2.0.4"
multer = "2.1.0"
parking_lot = "0.12.1"
rand = "0.8.5"
regex = "1.9.6"
reqwest-middleware = "0.2.3"
reqwest-retry = "0.3.0"
reqwest-tracing = "0.4.6"
rmp-serde = "1.1.2"
serde_qs = "0.12.0"
sha2 = "0.10.8"
sysinfo = "0.29.10"
task-local-extensions = "0.1.4"
toml = "0.8.2"
tracing = "0.1.37"
tracing-appender = "0.2.2"
url = "2.4.1"

[dependencies.argon2]
version = "0.5.2"
features = ["std"]

[dependencies.async-openai]
version = "0.14.3"
optional = true

[dependencies.ctr]
version = "0.9.2"
optional = true

[dependencies.chrono]
version = "0.4.31"
features = ["serde"]

[dependencies.datafusion]
version = "31.0.0"
optional = true

[dependencies.lru]
version = "0.12.0"
optional = true

[dependencies.minijinja]
version = "1.0.8"
optional = true
features = ["debug", "loader"]

[dependencies.opendal]
version = "0.40.0"
optional = true
features = ["layers-all"]

[dependencies.printpdf]
version = "0.6.0"
optional = true

[dependencies.reqwest]
version = "0.11.22"
default-features = false
features = [
    "cookies",
    "gzip",
    "json",
    "multipart",
    "stream",
]

[dependencies.serde]
version = "1.0.188"
features = ["derive"]

[dependencies.serde_json]
version = "1.0.107"
features = ["raw_value"]

[dependencies.sm3]
version = "0.4.2"
optional = true

[dependencies.sm4]
version = "0.5.1"
optional = true

[dependencies.sqlx]
version = "0.7.2"
optional = true
features = [
    "chrono",
    "rust_decimal",
    "uuid",
]

[dependencies.tera]
version = "1.19.1"
optional = true

[dependencies.totp-rs]
version = "5.4.0"
optional = true
features = ["otpauth", "qr"]

[dependencies.tracing-subscriber]
version = "0.3.17"
features = [
    "env-filter",
    "json",
    "local-time",
    "parking_lot",
]

[dependencies.unic-langid]
version = "0.9.1"
features = ["macros"]

[dependencies.utoipa]
version = "3.5.0"
features = [
    "non_strict_integers",
    "preserve_order",
    "preserve_path_order",
    "uuid",
]

[dependencies.uuid]
version = "1.4.1"
features = [
    "fast-rng",
    "serde",
    "v4",
    "v7",
]

[dev-dependencies]
anyhow = "1.0.75"
base64-simd = "0.8.0"
criterion = "0.5.1"
ryu = "1.0.15"
tinyvec = { version = "1.6.0", features = ["alloc"] }
uuid-simd = "0.8.0"

[[bench]]
name = "criterion_main"
harness = false
