[package]
name = "zino-core"
description = "Core types and traits for zino."
version = "0.4.1"
rust-version = "1.68"
edition = "2021"
license = "MIT"
categories = ["asynchronous", "network-programming", "web-programming::http-server"]
keywords = ["http", "web", "framework"]
homepage = "https://github.com/photino/zino"
repository = "https://github.com/photino/zino"
documentation = "https://docs.rs/zino-core"
readme = "README.md"

[package.metadata.docs.rs]
features = ["axum"]

[dependencies]
aes-gcm-siv = "0.11.1"
async-trait = "0.1.60"
base64 = "0.21.0"
bytes = "1.3.0"
cron = "0.12.0"
futures = "0.3.25"
hmac = "0.12.1"
http = "0.2.8"
http-body = "0.4.5"
http-types = "2.12.0"
hyper = "0.14.23"
lru = "0.9.0"
metrics = "0.20.1"
metrics-exporter-prometheus = "0.11.0"
metrics-exporter-tcp = "0.7.0"
parking_lot = "0.12.1"
rand = "0.8.5"
reqwest-middleware = "0.2.0"
reqwest-retry = "0.2.1"
reqwest-tracing = "0.4.0"
serde_json = "1.0.91"
serde_qs = "0.11.0"
serde_urlencoded = "0.7.1"
task-local-extensions = "0.1.3"
toml = "0.5.10"
tracing = "0.1.37"
tracing-appender = "0.2.2"
url = "2.3.1"

[dependencies.chrono]
version = "0.4.23"
features = ["serde"]

[dependencies.serde]
version = "1.0.152"
features = ["derive"]

[dependencies.reqwest]
version = "0.11.13"
features = ["cookies", "gzip", "brotli", "deflate", "json", "multipart", "stream"]

[dependencies.sqlx]
version = "0.6.2"
features = ["runtime-tokio-native-tls", "postgres", "uuid", "chrono", "json"]

[dependencies.tracing-subscriber]
version = "0.3.16"
features = ["env-filter", "json", "local-time"]

[dependencies.uuid]
version = "1.2.2"
features = ["fast-rng", "serde", "v4", "v7"]