[package]
name = "dioxus-desktop"
description = "An example for Dioxus desktop integration."
version = "0.1.1"
rust-version = "1.72"
edition = "2021"
publish = false

[dependencies]
dioxus = "0.4.0"
dioxus-router = "0.4.1"
serde_json = "1.0.107"
tracing = "0.1.39"

[dependencies.dioxus-free-icons]
version = "0.7.0"
features = [
    "bootstrap",
    "font-awesome-brands",
    "font-awesome-solid",
    "octicons",
]

[dependencies.serde]
version = "1.0.189"
features = ["derive"]

[dependencies.zino]
path = "../../zino"
version = "0.13.2"
features = ["dioxus"]

[dependencies.zino-core]
path = "../../zino-core"
version = "0.14.2"
features = ["orm-sqlite"]

[dependencies.zino-model]
path = "../../zino-model"
version = "0.11.2"
