[package]
name = "dioxus-desktop"
description = "An example for Dioxus desktop integration."
version = "0.2.3"
rust-version = "1.75"
edition = "2021"
publish = false

[dependencies]
dioxus = "0.4.3"
dioxus-router = "0.4.3"
tracing = "0.1.40"

[dependencies.dioxus-free-icons]
version = "0.7.0"
features = [
    "bootstrap",
    "font-awesome-brands",
    "font-awesome-solid",
    "octicons",
]

[dependencies.serde]
version = "1.0.195"
features = ["derive"]

[dependencies.zino]
path = "../../zino"
version = "0.17.2"
features = ["dioxus-desktop"]

[dependencies.zino-core]
path = "../../zino-core"
version = "0.18.2"
features = ["orm-sqlite"]

[dependencies.zino-model]
path = "../../zino-model"
version = "0.15.2"

[dependencies.zino-dioxus]
path = "../../zino-dioxus"
version = "0.2.3"
