[package]
name = "dioxus-desktop"
description = "An example for Dioxus desktop integration."
version = "0.1.4"
rust-version = "1.73"
edition = "2021"
publish = false

[dependencies]
dioxus = "0.4.0"
dioxus-router = "0.4.1"
tracing = "0.1.40"

[dependencies.dioxus-free-icons]
version = "0.7.0"
features = [
    "bootstrap",
    "font-awesome-brands",
    "font-awesome-solid",
    "octicons",
]

[dependencies.serde]
version = "1.0.193"
features = ["derive"]

[dependencies.zino]
path = "../../zino"
version = "0.15.4"
features = ["dioxus-desktop"]

[dependencies.zino-core]
path = "../../zino-core"
version = "0.16.4"
features = ["orm-sqlite"]

[dependencies.zino-model]
path = "../../zino-model"
version = "0.13.4"

[dependencies.zino-dioxus]
path = "../../zino-dioxus"
version = "0.1.4"
