# --env=dev

name = "data-cube"
version = "0.1.3"

[dirs]
uploads = "local/uploads"

[window]
title = "DataCube"
theme = "Light"
transparent = false

[database]
namespace = "dc"
max-rows = 10000

[[sqlite]]
database = "local/data/main.db"

[tracing]
filter = "info,sqlx=info,zino=trace,zino_core=trace"
