# --env=prod

name = "data-cube"
version = "0.1.3"

[dirs]
uploads = "local/uploads"

[window]
title = "DataCube"
theme = "Dark"

[database]
type = "sqlite"
namespace = "dc"

[[sqlite]]
database = "local/data/main.db"

[tracing]
filter = "warn"
