# --env=prod

name = "data-cube"
version = "0.1.3"

[dirs]
uploads = "local/uploads"

[window]
title = "DataCube"
theme = "Dark"
transparent = false

[desktop]
icon = "public/favicon.ico"
stylesheets = [
    "public/css/bulma.min.css",
    "public/css/custom.css",
]

[database]
type = "sqlite"
namespace = "dc"

[[sqlite]]
database = "local/data/main.db"

[tracing]
filter = "warn"
