[package]
name = "zino-cli"
description = "CLI tools for zino."
version = "0.1.2"
rust-version = "1.73"
edition = "2021"
license = "MIT"
categories = ["command-line-utilities", "network-programming", "web-programming"]
keywords = ["cli", "gui", "zino", "dioxus"]
homepage = "https://github.com/photino/zino"
repository = "https://github.com/photino/zino"
documentation = "https://docs.rs/zino-cli"
readme = "README.md"

[[bin]]
name = "zli"
path = "src/main.rs"

[dependencies]
log = "0.4.20"

[dependencies.clap]
version = "4.4.7"
features = ["derive"]

[dependencies.zino-core]
path = "../zino-core"
version = "0.15.3"
