[package]
name = "axum-app"
version = "0.4.7"
rust-version = "1.68"
edition = "2021"
publish = false

[dependencies]
axum = "0.6.4"
fluent = "0.16.0"
serde_json = "1.0.92"
tracing = "0.1.37"

[dependencies.zino]
path = "../../zino"
version = "0.5.3"
features = ["axum"]

[dependencies.zino-core]
path = "../../zino-core"
version = "0.5.3"
features = ["view"]

[dependencies.zino-model]
path = "../../zino-model"
version = "0.3.10"
