[package]
name = "axum-app"
description = "An example for axum integration."
version = "0.7.3"
rust-version = "1.70"
edition = "2021"
publish = false

[dependencies]
axum = "0.6.18"
fluent = "0.16.0"
serde_json = "1.0.96"
tracing = "0.1.37"
rbatis = "4.3.4"
rbdc-mysql = "4.3.5"
rbs = "4.3.2"

[dependencies.zino]
path = "../../zino"
version = "0.9.0"
features = ["axum"]

[dependencies.zino-core]
path = "../../zino-core"
version = "0.10.0"
features = [
    "connector",
    "connector-arrow",
    "orm-mysql",
    "view-tera",
]

[dependencies.zino-model]
path = "../../zino-model"
version = "0.7.0"
