[package]
name = "axum-app"
version = "0.4.2"
rust-version = "1.68"
edition = "2021"
publish = false

[dependencies]
axum = "0.6.2"
serde_json = "1.0.91"
tracing = "0.1.37"

[dependencies.zino]
path = "../../zino"
version = "0.4.2"
features = ["axum"]

[dependencies.zino-model]
path = "../../zino-model"
version = "0.3.4"
