[package]
name = "axum-app"
description = "An example for axum integration."
version = "0.9.2"
rust-version = "1.72"
edition = "2021"
publish = false

[dependencies]
axum = "0.6.20"
fluent = "0.16.0"
serde_json = "1.0.107"
tracing = "0.1.39"

[dependencies.serde]
version = "1.0.189"
features = ["derive"]

[dependencies.zino]
path = "../../zino"
version = "0.13.2"
features = ["axum"]

[dependencies.zino-core]
path = "../../zino-core"
version = "0.14.2"
features = [
    "connector",
    "connector-arrow",
    "crypto-sm",
    "orm-mysql",
    "view-tera",
]

[dependencies.zino-derive]
path = "../../zino-derive"
version = "0.11.2"

[dependencies.zino-model]
path = "../../zino-model"
version = "0.11.2"
