[package]
name = "axum-app"
description = "An example for axum integration."
version = "0.5.0"
rust-version = "1.68"
edition = "2021"
publish = false

[dependencies]
axum = "0.6.7"
fluent = "0.16.0"
serde_json = "1.0.93"
tracing = "0.1.37"

[dependencies.zino]
path = "../../zino"
version = "0.5.4"
features = ["axum"]

[dependencies.zino-model]
path = "../../zino-model"
version = "0.4.0"
