[package]
name = "axum-app"
description = "An example for axum integration."
version = "0.5.3"
rust-version = "1.68"
edition = "2021"
publish = false

[dependencies]
axum = "0.6.8"
fluent = "0.16.0"
serde_json = "1.0.93"
tracing = "0.1.37"

[dependencies.zino]
path = "../../zino"
version = "0.5.7"
features = ["axum"]

[dependencies.zino-core]
path = "../../zino-core"
version = "0.6.3"
features = ["connector", "connector-arrow"]

[dependencies.zino-model]
path = "../../zino-model"
version = "0.4.3"
