[package]
name = "axum-app"
description = "An example for axum integration."
version = "0.8.2"
rust-version = "1.72"
edition = "2021"
publish = false

[dependencies]
axum = "0.6.20"
fluent = "0.16.0"
serde_json = "1.0.105"
tracing = "0.1.37"

[dependencies.serde]
version = "1.0.186"
features = ["derive"]

[dependencies.zino]
path = "../../zino"
version = "0.11.0"
features = ["axum", "export-pdf"]

[dependencies.zino-core]
path = "../../zino-core"
version = "0.12.0"
features = [
    "connector",
    "connector-arrow",
    "orm-mysql",
    "view-tera",
]

[dependencies.zino-derive]
path = "../../zino-derive"
version = "0.9.0"

[dependencies.zino-model]
path = "../../zino-model"
version = "0.9.0"
