[package]
name = "axum-app"
description = "An example for axum integration."
version = "0.6.5"
rust-version = "1.70"
edition = "2021"
publish = false

[dependencies]
axum = "0.6.18"
fluent = "0.16.0"
serde_json = "1.0.96"
tracing = "0.1.37"

[dependencies.zino]
path = "../../zino"
version = "0.8.3"
features = ["axum"]

[dependencies.zino-core]
path = "../../zino-core"
version = "0.9.2"
features = [
    "connector",
    "connector-arrow",
    "orm-mysql",
]

[dependencies.zino-model]
path = "../../zino-model"
version = "0.6.0"
