[package]
name = "zino"
description = "A minimal MVC framework."
version = "0.2.0"
edition = "2021"
license = "MIT"
homepage = "https://github.com/photino/zino"
repository = "https://github.com/photino/zino"
documentation = "https://docs.rs/zino"
readme = "README.md"

[features]
default = ["axum-server"]
axum-server = ["axum", "tokio", "tokio-stream", "tower", "tower-http"]

[dependencies]
async-trait = { version = "0.1.60" }
axum = { version = "0.6.1", features = ["ws"], optional = true }
futures = { version = "0.3.25" }
http-types = { version = "2.12.0" }
hyper = { version = "0.14.23" }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = { version = "1.0.91" }
serde_qs = { version = "0.10.1" }
serde_urlencoded = { version = "0.7.1" }
toml = { version = "0.5.10" }
tokio = { version = "1.23.0", features = ["rt-multi-thread", "sync"], optional = true }
tokio-stream = { version = "0.1.11", features = ["sync"], optional = true }
tower = { version = "0.4.13", optional = true }
tower-http = { version = "0.1.1", features = ["add-extension", "fs"], optional = true }

[dependencies.zino-core]
path = "../zino-core"
version = "0.2.0"