[package]
name = "zino"
description = "Full-featured web application framework for Rust."
version = "0.6.4"
rust-version = "1.70"
edition = "2021"
license = "MIT"
categories = ["asynchronous", "network-programming", "web-programming::http-server"]
keywords = ["http", "web", "framework"]
homepage = "https://github.com/photino/zino"
repository = "https://github.com/photino/zino"
documentation = "https://docs.rs/zino"
readme = "README.md"

[package.metadata.docs.rs]
features = ["axum"]

[features]
axum = [
    "dep:axum",
    "dep:tokio",
    "dep:tokio-stream",
    "dep:tower",
    "dep:tower-http",
    "zino-core/runtime-tokio",
]

[dependencies]
async-trait = "0.1.68"
futures = "0.3.28"
hyper = "0.14.25"
parking_lot = "0.12.1"
serde_json = "1.0.95"
toml = "0.7.3"
tracing = "0.1.37"

[dependencies.axum]
version = "0.6.12"
optional = true
features = ["ws"]

[dependencies.serde]
version = "1.0.159"

[dependencies.tokio]
version = "1.27.0"
optional = true
features = ["parking_lot", "rt-multi-thread"]

[dependencies.tokio-stream]
version = "0.1.12"
optional = true
features = ["sync"]

[dependencies.tower]
version = "0.4.13"
optional = true
features = ["timeout"]

[dependencies.tower-cookies]
version = "0.9.0"
features= ["signed"]

[dependencies.tower-http]
version = "0.4.0"
optional = true
features = [
    "add-extension",
    "compression-br",
    "compression-gzip",
    "decompression-br",
    "decompression-gzip",
    "cors",
    "fs",
    "trace",
]

[dependencies.zino-core]
path = "../zino-core"
version = "0.8.0"
features = ["orm", "view"]