[package]
name = "zino"
description = "Full-featured web application framework for Rust."
version = "0.10.2"
rust-version = "1.72"
edition = "2021"
license = "MIT"
categories = ["asynchronous", "network-programming", "web-programming::http-server"]
keywords = ["http", "web", "framework"]
homepage = "https://github.com/photino/zino"
repository = "https://github.com/photino/zino"
documentation = "https://docs.rs/zino"
readme = "README.md"

[package.metadata.docs.rs]
features = ["axum"]

[features]
actix = [
    "dep:actix-cors",
    "dep:actix-files",
    "dep:actix-web",
    "dep:tracing-actix-web",
    "utoipa-swagger-ui/actix-web",
    "zino-core/runtime-tokio",
]
axum = [
    "dep:axum",
    "dep:tokio",
    "dep:tokio-stream",
    "dep:tower",
    "dep:tower-http",
    "utoipa-swagger-ui/axum",
    "zino-core/runtime-tokio",
]
default = ["orm", "view"]
orm = ["zino-core/orm"]
view = ["zino-core/view"]

[dependencies]
async-trait = "0.1.71"
cfg-if = "1.0"
futures = "0.3.28"
hyper = "0.14.27"
parking_lot = "0.12.1"
serde = "1.0.171"
serde_json = "1.0.103"
toml = "0.7.6"
tracing = "0.1.37"

[dependencies.actix-cors]
version = "0.6.4"
optional = true

[dependencies.actix-files]
version = "0.6.2"
optional = true

[dependencies.actix-web]
version = "4.3.1"
optional = true
default-features = false
features = [
    "compress-brotli",
    "compress-gzip",
    "cookies",
    "secure-cookies",
]

[dependencies.tracing-actix-web]
version = "0.7.5"
optional = true
features = ["opentelemetry_0_19"]

[dependencies.axum]
version = "0.6.19"
optional = true
default-features = false
features = [
    "matched-path",
    "original-uri",
    "query",
    "tokio",
    "tracing",
    "ws",
]

[dependencies.utoipa-swagger-ui]
version = "3.1.4"
optional = true

[dependencies.tokio]
version = "1.29.1"
optional = true
features = ["parking_lot", "rt-multi-thread"]

[dependencies.tokio-stream]
version = "0.1.14"
optional = true
features = ["sync"]

[dependencies.tower]
version = "0.4.13"
optional = true
features = ["timeout"]

[dependencies.tower-cookies]
version = "0.8.0"
features= ["signed"]

[dependencies.tower-http]
version = "0.4.1"
optional = true
features = [
    "add-extension",
    "compression-br",
    "compression-gzip",
    "cors",
    "decompression-br",
    "decompression-gzip",
    "fs",
    "trace",
]

[dependencies.zino-core]
path = "../zino-core"
version = "0.11.2"
