[package]
name = "zino"
description = "Full featured web application framework for Rust."
version = "0.3.1"
rust-version = "1.68"
edition = "2021"
license = "MIT"
categories = ["asynchronous", "network-programming", "web-programming::http-server"]
keywords = ["http", "web", "framework"]
homepage = "https://github.com/photino/zino"
repository = "https://github.com/photino/zino"
documentation = "https://docs.rs/zino"
readme = "README.md"

[features]
default = ["axum-server"]
axum-server = ["dep:axum", "dep:tokio", "dep:tokio-stream", "dep:tower", "dep:tower-http"]

[dependencies]
async-trait = { version = "0.1.60" }
axum = { version = "0.6.1", features = ["ws"], optional = true }
cfg-if = { version = "1.0.0" }
futures = { version = "0.3.25" }
http-types = { version = "2.12.0" }
hyper = { version = "0.14.23" }
parking_lot = { version = "0.12.1" }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = { version = "1.0.91" }
serde_qs = { version = "0.10.1" }
serde_urlencoded = { version = "0.7.1" }
tokio = { version = "1.24.1", features = ["rt-multi-thread", "sync", "parking_lot"], optional = true }
tokio-stream = { version = "0.1.11", features = ["sync"], optional = true }
toml = { version = "0.5.10" }
tower = { version = "0.4.13", features = ["timeout"], optional = true }
tower-http = { version = "0.3.5", features = ["full"], optional = true }
tracing = { version = "0.1.37" }

[dependencies.zino-core]
path = "../zino-core"
version = "0.3.1"