[package]
name = "zino"
description = "Next-generation framework for composable applications in Rust."
version = "0.13.1"
rust-version = "1.72"
edition = "2021"
license = "MIT"
categories = ["asynchronous", "network-programming", "web-programming::http-server"]
keywords = ["http", "web", "framework"]
homepage = "https://github.com/photino/zino"
repository = "https://github.com/photino/zino"
documentation = "https://docs.rs/zino"
readme = "README.md"

[package.metadata.docs.rs]
features = ["axum"]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]

[features]
actix = [
    "dep:actix-cors",
    "dep:actix-files",
    "dep:actix-web",
    "dep:tracing-actix-web",
    "utoipa/actix_extras",
    "utoipa-rapidoc/actix-web",
    "zino-core/runtime-tokio",
]
axum = [
    "dep:axum",
    "dep:tokio",
    "dep:tokio-stream",
    "dep:tower",
    "dep:tower-http",
    "utoipa/axum_extras",
    "utoipa-rapidoc/axum",
    "zino-core/runtime-tokio",
]
dioxus = [
    "dep:dioxus",
    "dep:dioxus-desktop",
    "dep:dioxus-router",
    "dep:tokio",
]
default = ["orm", "view"]
orm = ["zino-core/orm"]
view = ["zino-core/view"]
export-pdf = ["zino-core/format-pdf"]

[dependencies]
async-trait = "0.1.73"
cfg-if = "1.0"
futures = "0.3.28"
hyper = "0.14.27"
parking_lot = "0.12.1"
serde = "1.0.189"
serde_json = "1.0.107"
toml = "0.8.2"
tracing = "0.1.39"

[dependencies.actix-cors]
version = "0.6.4"
optional = true

[dependencies.actix-files]
version = "0.6.2"
optional = true

[dependencies.actix-web]
version = "4.4.0"
optional = true
default-features = false
features = [
    "compress-brotli",
    "compress-gzip",
    "cookies",
    "secure-cookies",
]

[dependencies.axum]
version = "0.6.20"
optional = true
default-features = false
features = [
    "matched-path",
    "original-uri",
    "query",
    "tokio",
    "tracing",
    "ws",
]

[dependencies.dioxus]
version = "0.4.0"
optional = true

[dependencies.dioxus-desktop]
version = "0.4.0"
optional = true

[dependencies.dioxus-router]
version = "0.4.1"
optional = true

[dependencies.tokio]
version = "1.32.0"
optional = true
features = ["parking_lot", "rt-multi-thread"]

[dependencies.tokio-stream]
version = "0.1.14"
optional = true
features = ["sync"]

[dependencies.tower]
version = "0.4.13"
optional = true
features = ["timeout"]

[dependencies.tower-cookies]
version = "0.8.0"
features= ["signed"]

[dependencies.tower-http]
version = "0.4.4"
optional = true
features = [
    "add-extension",
    "compression-br",
    "compression-gzip",
    "cors",
    "decompression-br",
    "decompression-gzip",
    "fs",
    "trace",
]

[dependencies.tracing-actix-web]
version = "0.7.7"
optional = true
features = ["opentelemetry_0_20"]

[dependencies.utoipa]
version = "4.0.0"
optional = true

[dependencies.utoipa-rapidoc]
version = "1.0.0"
optional = true

[dependencies.zino-core]
path = "../zino-core"
version = "0.14.1"
