[package]
name = "zino"
description = "Full-featured web application framework for Rust."
version = "0.5.4"
rust-version = "1.68"
edition = "2021"
license = "MIT"
categories = ["asynchronous", "network-programming", "web-programming::http-server"]
keywords = ["http", "web", "framework"]
homepage = "https://github.com/photino/zino"
repository = "https://github.com/photino/zino"
documentation = "https://docs.rs/zino"
readme = "README.md"

[package.metadata.docs.rs]
all-features = true

[features]
axum = [
    "dep:axum",
    "dep:tokio",
    "dep:tokio-stream",
    "dep:tower",
    "dep:tower-http",
]

[dependencies]
async-trait = "0.1.64"
futures = "0.3.26"
hyper = "0.14.24"
parking_lot = "0.12.1"
serde_json = "1.0.93"
serde_urlencoded = "0.7.1"
toml = "0.7.2"
tracing = "0.1.37"

[dependencies.axum]
version = "0.6.4"
features = ["ws"]
optional = true

[dependencies.serde]
version = "1.0.152"
features = ["derive"]

[dependencies.tokio]
version = "1.25.0"
features = ["rt-multi-thread", "sync", "parking_lot"]
optional = true

[dependencies.tokio-stream]
version = "0.1.11"
features = ["sync"]
optional = true

[dependencies.tower]
version = "0.4.13"
features = ["timeout"]
optional = true

[dependencies.tower-cookies]
version = "0.9.0"
features= ["signed"]

[dependencies.tower-http]
version = "0.3.5"
features = [
    "add-extension",
    "compression-br",
    "compression-gzip",
    "cors",
    "fs",
    "trace",
]
optional = true

[dependencies.zino-core]
path = "../zino-core"
version = "0.6.0"