
name = "data-cube"
version = "0.2.2"

[main]
host = "127.0.0.1"
port = 6080

[[standby]]
host = "127.0.0.1"
port = 6081

[[standby]]
host = "127.0.0.1"
port = 6082

[database]
type = "postgres"
schema = "public"
namespace = "dc"

[[postgres]]
host = "localhost"
port = 5432
database = "data_cube"
user = "postgres"
password = "QAx01wnh1i5ER713zfHmZi6dIUYn/Iq9ag+iUGtvKzEFJFYW"

[tracing]
filter = "info,sqlx=trace,tower_http=trace,zino=trace,zino_core=trace"