
name = "data-cube"
version = "0.4.7"

[main]
host = "127.0.0.1"
port = 6080

[[standby]]
host = "127.0.0.1"
port = 6081

[[standby]]
host = "127.0.0.1"
port = 6082

[database]
type = "postgres"
namespace = "dc"

[[postgres]]
host = "127.0.0.1"
port = 5432
database = "data_cube"
username = "postgres"
password = "5YMz8c7me8scYFWn5epaJbvK0/RFJ1hGYNb5A17q/hiQw9ok"

[tracing]
filter = "info,sqlx=trace,tower_http=trace,zino=trace,zino_core=trace"
display-filename = false
display-line-number = false
display-span-list = false

[metrics]
exporter = "prometheus"
host = "127.0.0.1"
port = 9000

[[connector]]
type = "arrow"
name = "education"

[[connector.tables]]
name = "students"
path = "./assets/data/education/students.csv"
