[package]
name = "zino-dioxus"
description = "Dioxus components for zino."
version = "0.2.3"
rust-version = "1.75"
edition = "2021"
license = "MIT"
categories = ["gui", "network-programming", "web-programming"]
keywords = ["zino", "dioxus", "components"]
homepage = "https://github.com/zino-rs/zino"
repository = "https://github.com/zino-rs/zino"
documentation = "https://docs.rs/zino-dioxus"
readme = "README.md"

[dependencies]
dioxus = "0.4.3"
dioxus-core = "0.4.3"
dioxus-router = "0.4.3"
dioxus-free-icons = "0.7.0"
rust_decimal = "1.33.1"
smallvec = "1.11.1"

[dependencies.chrono]
version = "0.4.31"
features = ["serde"]

[dependencies.tokio]
version = "1.35.1"
features = ["time"]

[dependencies.uuid]
version = "1.6.1"
features = [
    "fast-rng",
    "serde",
    "v4",
    "v7",
]

[dependencies.zino-core]
path = "../zino-core"
version = "0.18.2"
