[package]
name = "actix-app"
description = "An example for actix-web integration."
version = "0.2.2"
rust-version = "1.72"
edition = "2021"
publish = false

[dependencies]
actix-web = "4.3.1"
fluent = "0.16.0"
serde_json = "1.0.105"
tracing = "0.1.37"

[dependencies.serde]
version = "1.0.183"
features = ["derive"]

[dependencies.zino]
path = "../../zino"
version = "0.11.0"
features = ["actix", "export-pdf"]

[dependencies.zino-core]
path = "../../zino-core"
version = "0.12.0"
features = [
    "connector",
    "connector-arrow",
    "orm-postgres",
    "view-minijinja",
]

[dependencies.zino-derive]
path = "../../zino-derive"
version = "0.9.0"

[dependencies.zino-model]
path = "../../zino-model"
version = "0.9.0"
