[package]
name = "actix-app"
description = "An example for actix-web integration."
version = "0.1.4"
rust-version = "1.70"
edition = "2021"
publish = false

[dependencies]
actix-web = "4.3.1"
fluent = "0.16.0"
serde_json = "1.0.96"
tracing = "0.1.37"
rbatis = "4.3.6"
rbdc-mysql = "4.3.5"
rbs = "4.3.2"

[dependencies.serde]
version = "1.0.162"
features = ["derive"]

[dependencies.zino]
path = "../../zino"
version = "0.9.4"
features = ["actix"]

[dependencies.zino-core]
path = "../../zino-core"
version = "0.10.4"
features = [
    "connector",
    "connector-arrow",
    "orm-postgres",
    "view-minijinja",
]

[dependencies.zino-derive]
path = "../../zino-derive"
version = "0.7.5"

[dependencies.zino-model]
path = "../../zino-model"
version = "0.7.5"
