[package]
name = "actix-app"
description = "An example for actix-web integration."
version = "0.5.1"
rust-version = "1.75"
edition = "2021"
publish = false

[dependencies]
actix-web = "4.4.0"
tracing = "0.1.40"

[dependencies.serde]
version = "1.0.195"
features = ["derive"]

[dependencies.zino]
path = "../../zino"
version = "0.17.1"
features = ["actix"]

[dependencies.zino-core]
path = "../../zino-core"
version = "0.18.1"
features = ["orm-postgres", "view-minijinja"]

[dependencies.zino-derive]
path = "../../zino-derive"
version = "0.15.1"

[dependencies.zino-model]
path = "../../zino-model"
version = "0.15.1"
