[package]
name = "actix-app"
description = "An example for actix-web integration."
version = "0.0.1"
rust-version = "1.70"
edition = "2021"
publish = false

[dependencies]
actix-web = "4.3.1"
fluent = "0.16.0"
serde_json = "1.0.96"
tracing = "0.1.37"

[dependencies.zino]
path = "../../zino"
version = "0.7.1"
features = ["actix"]

[dependencies.zino-core]
path = "../../zino-core"
version = "0.8.2"
features = ["connector", "connector-arrow"]

[dependencies.zino-model]
path = "../../zino-model"
version = "0.5.2"
