name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install 1.75
      run: rustup install 1.75
    - name: Set default toolchain
      run: rustup default 1.75
    - name: Build
      run: cargo build --features axum,full --verbose
    - name: Run tests
      run: cargo test --verbose
